= Help LGBTQIA refugees in East Africa survive to safety

:date: 05-01-2026 16:44:00

My name is James Goebel and I am working with Augustine Kayemba to provide necessary survival funds for food, medical attention, and building a fence to protect this community from frequent homophobic attacks. Please read Augustine's story below:

My name is Augustine Kayemba, and I am an LGBTIQ leader and representative here in Kenya, where we have faced a great deal of homophobia in this environment, including from fellow refugees.

Unfortunately, UNHCR staff, including medical attendants, are homophobic to us and don’t provide services to us. This has been reported several times to the people responsible but help has been in vain. Thus, seeking support from fellow LGBTIQ organizations and individual well-wishers to attain medication from private hospitals in the camp has been difficult.

Additionally, food provided to us, as distributed at present by the UNHCR, is not enough to sustain us for a month.
Thus, we are seeking support to overcome scarcity and hunger.

We will be very glad to receive any positive feedback in terms of financial help, advice and advocacy support!
Many thanks.

== Life at Kakuma

Generally life at Kakuma refugee camp is extremely hard for the LGBTQI community due to rampant HOMOPHOBIA within the camp. This is witnessed through daily attacks by homophobic fellow refugees and the co-host community.

LGBTQI refugees live under great fear whereby we're being targeted by the homophobes; this has resulted in severe injuries where these homophobes ambush when armed with machetes. Over time, property has been also lost and even lives where we have so far lost three of our mates. This was witnessed in the recent attack when two LGBTQI refugees were set on fire where they suffered third degree burns, which resulted in one losing his life while the other is on life support in hospital.

In addition, sexual harassment has also been witnessed here at Kakuma refugee camp to the LGBTQI community. Lesbians on several occasions have been raped not once but twice. Beyond any reasonable doubt, this has made Kakuma the most hostile land for LGBTQI community.

Furthermore, the LGBTQI community lives under great suffering due to the fact they are willing to work to earn a living but fail to get employment opportunities due to their sexual orientation. This has made life so much harder for the minority group, being marginalized amidst this arid area of Kakuma. We have faced various attacks from homophobes and also illness related to poor standards of living.
Even so, despite all the misery, we try to find some time to kill the stress when celebrating official LGBTIQ days and festivals. Below is when we celebrated the Pride Day and also had some couples officially get married while maintaining a low profile.

Yours sincerely,

Augustine Kayemba

P.S. Please donate to our https://www.gofundme.com/f/survival-funds-for-lgbtq-kakuma-refugees/cl/s[GoFundMe]
